import { Montserrat } from "next/font/google";

import "./globals.css";
import ProviderRedux from "@/components/api/Provider";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "First Road",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ProviderRedux>
        <body className={`${montserrat.className} antialiased`}>
          {children}
        </body>
      </ProviderRedux>
    </html>
  );
}
